- hosts: all
  become: yes
  tasks:
    - name: Update
      apt: update_cache=yes cache_valid_time=3600

    - name: Upgrade paquetes apt
      apt: upgrade=dist force_apt_get=yes

    - name: Instalar Apache2
      apt: name=apache2 state=latest
    - name: Verificar Apache2 activo y en arranque
      service: name=apache2 state=started enabled=yes

    - name: Instalar Git
      apt: name=git state=latest

    - name: Installation install software-properties-common
      apt: name=software-properties-common

    - name: Descargar e instalar Composer
      shell: curl -sS https://getcomposer.org/installer | php
      args:
        chdir: /usr/src/
        creates: /usr/local/bin/composer
        warn: false
      become: yes
    - name: Agregar Composer a path global
      copy:
        dest: /usr/local/bin/composer
        group: root
        mode: '0755'
        owner: root
        src: /usr/src/composer.phar
        remote_src: yes
      become: yes
